queue:
  name: Default
  demands: maven


steps:
- task: Maven@1
  inputs:
    goals: "clean test"
    
- powershell: |
   # Write your powershell commands here.  
   Write-Host $(mysecret)
   displayName: PowerShell Script


